name: ROS-noetic-build-test

on: [push]

jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      CATKIN_WS: /home/catkin_ws
    steps:
    - uses: actions/checkout@v2

    - name: Setup ROS
      uses: ros-tooling/setup-ros@v0.2
      with: 
        required-ros-distributions: noetic

    - name: Install catkin tool
      run: sudo apt-get install python3-catkin-tools

    - name: Init workspace
      run: |
        source /opt/ros/noetic/setup.bash
        sudo mkdir -p ${CATKIN_WS}/src
        ln -s ${GITHUB_WORKSPACE} ${CATKIN_WS}/src/
    
    - name: pre build
      run: |
        source /opt/ros/noetic/setup.bash
        cd ${CATKIN_WS}/src/theta_driver
        git submodule update --init --recursive
        rosdep update
        rosdep install -i -y --from-paths ./

    - name: install gstremer and libuvc dependencies
      run: |
        sudo apt-get install libgstreamer1.0-0
        sudo apt-get install gstreamer1.0-plugins-base
        sudo apt-get install gstreamer1.0-plugins-good
        sudo apt-get install gstreamer1.0-plugins-bad
        sudo apt-get install gstreamer1.0-plugins-ugly
        sudo apt-get install gstreamer1.0-libav
        sudo apt-get install gstreamer1.0-doc
        sudo apt-get install gstreamer1.0-tools
        sudo apt-get install gstreamer1.0-x
        sudo apt-get install gstreamer1.0-alsa
        sudo apt-get install gstreamer1.0-gl
        sudo apt-get install gstreamer1.0-gtk3
        sudo apt-get install gstreamer1.0-qt5
        sudo apt-get install gstreamer1.0-pulseaudio
        sudo apt-get install libgstreamer-plugins-base1.0-dev
        sudo apt-get install libusb-1.0-0-dev

    - name: install ROS packages, dev dependencies and ci dependencies
      run: |
        sudo apt-get install ros-noetic-image-transport
        sudo apt-get install ros-noetic-cv-bridge
        sudo apt-get install rsync
        sudo apt-get install ccache
        sudo apt-get install clang-format-6.0

    - name: install libuvc-theta
      working-directory: ./home
      run: |
        git clone https://github.com/ricohapi/libuvc-theta.git
        cd libuvc-theta
        sudo mkdir build
        cd build
        cmake -DCMAKE_BUILD_TYPE=Release ..
        make
        make install
        ldconfig

    - name: build
      run: |
        source /opt/ros/noetic/setup.bash
        cd ${CATKIN_WS}
        catkin build